EXTRA_APPS = "gstreamer-tests ifupdown"
EXTRA_DRIVERS = ""
EXTRA_APPS_append_tegra124 = " mesa-demos"
EXTRA_APPS_append_tegra186 = " mesa-demos tegra-mmapi-samples cuda-samples"
EXTRA_DRIVERS_tegra186 = "kernel-modules"
EXTRA_APPS_append_tegra194 = " mesa-demos cuda-samples"
EXTRA_DRIVERS_tegra194 = "kernel-modules"
EXTRA_APPS_append_tegra210 = " mesa-demos tegra-mmapi-samples cuda-samples"
RDEPENDS_${PN}-apps += "${EXTRA_APPS} ${EXTRA_DRIVERS}"

